using System;
using System.Collections.Generic;
using System.Text;

namespace Top4ever.BLL.Enum
{
    public enum Command
    {
        ID_USERLOGIN = 1,
        ID_GET_SYSBASICDATA = 2,
        ID_GET_DESKBYNAME = 3,
        ID_UPDATE_DESKSTATUS = 4,
        ID_CREATE_SALESORDER = 5,
        ID_GET_SALESORDER = 6,
        ID_UPDATE_SALESORDER = 7,
        ID_PAYFORORDER = 8,
        ID_DELETE_SINGLEORDER = 9,
        ID_DELETE_WHOLEORDER = 10,
        ID_GET_DESKREALTIMEINFO = 11,
        ID_UPDATE_LADEORDERDETAILS = 12,
        ID_GET_ORDERLIST = 13,
        ID_SPLIT_SALESORDER  = 14,
        ID_ORDER_DESKOPERATE = 15,
        ID_CREATE_HANDOVER = 16,
        ID_CREATE_DAILYBALANCE = 17,
        ID_GET_REPORTDATABYHANDOVER = 18,
        ID_GET_REPORTDATABYDAILYSTATEMENT = 19,
        ID_CREATE_REMINDERORDER = 20,
        ID_GET_RIGHTSCODELIST = 21,
        ID_GET_DAILYTIMEINTERVAL = 22,
        ID_GET_ORDERLISTBYSEARCH = 23,
        ID_SWIPINGCARDTOLOGIN = 24,
        ID_GET_SALESORDERBYBILLSEARCH = 25,
        ID_DELETE_PAIDWHOLEORDER = 26,
        ID_CHECK_LASTDAILYSTATEMENT = 27,
        ID_UPDATE_ORDERSTATUS = 28,
        ID_DELETE_PAIDSINGLEORDER = 29,
        ID_MODIFY_PAIDORDER = 30,
        ID_CREATE_PREPAYORDER = 31,
        ID_GET_DELIVERYORDERLIST = 32,
        ID_UPDATE_TAKEOUTORDERSTATUS = 33,
        ID_CREATE_CUSTOMERINFO = 34,
        ID_UPDATE_CUSTOMERINFO = 35,
        ID_GET_CUSTOMERINFOBYPHONE = 36,
        ID_GET_ALLCUSTOMERINFO = 37,
        ID_GET_EMPLOYEEBYNO = 38,
        ID_GET_CUSTOMERORDER = 39,
        ID_CREATE_CUSTOMERORDER = 40,
        ID_GET_GOODSCHECKSTOCK = 41,
        ID_UPDATE_REDUCEDGOODSQTY = 42,
        ID_GET_VIPCARD = 43,
        ID_GET_VIPCARDTRADELIST = 44,
        ID_UPDATE_CARDPASSWORD = 45
    }
}
